version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  publish_core_console: true
  verbosity: minimal
after_test:
- cmd: dotnet pack src/ExcelDna.CellAddress -c Release
artifacts:
- path: '**\*.nupkg'
  name: Nuget
deploy:
- provider: NuGet
  server: https://www.nuget.org
  api_key:
    secure: oP40O3/X4sx3UIkkzrvdgwj+qGHE4hXGH1AAmQWOfv3jwYmOaxBZxf04stoqp83h
  skip_symbols: true
  artifact: Nuget